### PR TITLE
[ISSUE #4770] Empty class member cause NullpointerException

### LINKED ISSUE #4770: [Bug] Empty class member cause NullpointerException
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac

### EventMesh version

master

### What happened

Runtime（Storage：Local Rocketmq ） + Http Source Connector

image
请求的路径应该是：curl发送请求->CloudEvent->ConnectRecord-> runtime(storage)
然后我发现是在CloudEvent->ConnectRecord转化的过程中position属性为null：
image

但是关于消息写入的offset和partition这些属性 应该是由storage的相关模块写入，但是我在CloudEventUtil里看到了关于这个的todo？

### How to reproduce

run Runtime（Storage：Local Rocketmq ） + Http Source Connector

### Debug logs

```Java
2024-02-16 00:11:21,099 DEBUG [vert.x-eventloop-thread-0] ZlibCodecFactory(ZlibCodecFactory.java:39) - -Dio.netty.noJdkZlibDecoder: false
2024-02-16 00:11:21,099 DEBUG [vert.x-eventloop-thread-0] ZlibCodecFactory(ZlibCodecFactory.java:42) - -Dio.netty.noJdkZlibEncoder: false
2024-02-16 00:11:21,170 INFO  [vert.x-eventloop-thread-0] HttpSourceConnector(HttpSourceConnector.java:100) - [HttpSourceConnector] Succeed to convert payload into CloudEvent. StatusCode=200
2024-02-16 00:11:21,174 INFO  [pool-3-thread-1] CloudEventUtil(CloudEventUtil.java:69) - handle receive events testdata



Exception in thread "pool-2-thread-1" java.lang.NullPointerException
	at org.apache.eventmesh.openconnect.offsetmgmt.api.storage.OffsetStorageWriterImpl.writeOffset(OffsetStorageWriterImpl.java:57)
	at java.util.HashMap.forEach(HashMap.java:1290)
	at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1507)
	at org.apache.eventmesh.openconnect.SourceWorker.commitOffsets(SourceWorker.java:346)
	at org.apache.eventmesh.openconnect.SourceWorker.startPollAndSend(SourceWorker.java:219)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

### PR DESCRIPTION
**Pull request by scwlkq**
### Contribution Checklist

Fixes #4770 

### Modifications

1. 对writeOffset增加了对null的兼容
2. 删除了CloudEventUtil的注释（ // todo: recordPartition & recordOffset）因为openconnect模块实现了connector的offset相关。 这个注释的日期是23年8月 openconnect-offset是23年7月，或者说CloudEventUtil需要实现不同中间件offset的转化？

### Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

File: eventmesh-openconnect/eventmesh-openconnect-offsetmgmt-plugin/eventmesh-openconnect-offsetmgmt-api/src/main/java/org/apache/eventmesh/openconnect/offsetmgmt/api/storage/OffsetStorageWriterImpl.java [hunk 1]
```diff
@@ -53,9 +53,12 @@ public OffsetStorageWriterImpl(String connectorName, OffsetManagementService off
     }
 
     @Override
-    public void writeOffset(RecordPartition partition, RecordOffset position) {
-        ConnectorRecordPartition extendRecordPartition = new ConnectorRecordPartition(connectorName, partition.getPartition());
-        data.put(extendRecordPartition, position);
+    public void writeOffset(RecordPartition partition, RecordOffset offset) {
+        ConnectorRecordPartition extendRecordPartition = null;
+        if (partition != null && partition.getPartition() != null) {
+            extendRecordPartition = new ConnectorRecordPartition(connectorName, partition.getPartition());
```
Comment (Pil0tXia) [inline eventmesh-openconnect/eventmesh-openconnect-offsetmgmt-plugin/eventmesh-openconnect-offsetmgmt-api/src/main/java/org/apache/eventmesh/openconnect/offsetmgmt/api/storage/OffsetStorageWriterImpl.java:59]: No need to combine the `partition.getPartition() != null` condition, because the `partition` member of `RecordPartition` is a HashMap by default and it won't be null. 

If it is set to null mistakenly, then an exception should be thrown from where it is called.

https://github.com/apache/eventmesh/blob/5cc065f1a29d7827a5243d81c32722e0cc85ebc9/eventmesh-openconnect/eventmesh-openconnect-offsetmgmt-plugin/eventmesh-openconnect-offsetmgmt-api/src/main/java/org/apache/eventmesh/openconnect/offsetmgmt/api/data/RecordPartition.java#L24-L32

**Review by Pil0tXia — CHANGES_REQUESTED** [review]

**Review by Pil0tXia — APPROVED** [review]

**Review by mxsm — APPROVED** [review]
LGTM
