### PR TITLE
[ISSUE #4659] Fix HTTP source connector stop after receiving an invalid request

### LINKED ISSUE #4659: [Bug] HTTP source connector stop after receiving an invalid request
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Linux

### EventMesh version

master

### What happened

 HTTP source connector stop after receiving an request without attribute `subject` and never response again.

### Reproduce
1. start http connector server
2. send an invalid request without `subject`, such as 
```shell
curl --location --request POST 'http://localhost:3755/test' \
--header 'ce-id: 11' \
--header 'ce-specversion: 1.0' \
--header 'ce-type: com.example.someevent' \
--header 'ce-source: /mycontext' \
# --header 'ce-subject: test' \
--header 'Content-Type: text/plain' \
--data-raw 'aaa'
```
3. http connector server stop forever

### Analysis 
In `HttpSourceConnector#poll`, the conversion from cloudevent to connectRecord is performed.
image

If a cloudevent contains null `subject`, `connectRecord.addExtension("topic", event.getSubject())` will throw unexpected NPE, which will stop the connector server.
image

### Fix
Check `subject` before saving cloudevents. We don't need to check other attributes like `id`, `source`, `type`,etc. Because they are required arrtibutes of cloudevents and cloudevents-sdk will do the check in `toEvent()`. 
```java
VertxMessageFactory.createReader(ctx.request())
                    .map(r -> {
                        CloudEvent event = r.toEvent();
                        if (event.getSubject() == null) {
                            throw new IllegalStateException("attribute 'subject' cannot be null");
                        }
                        return event;
                    })
setting others...
```

### Debug logs

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

### PR DESCRIPTION
**Pull request by Fungx**
Fixes #4659.

### Motivation

*Explain the content here.*
*Explain why you want to make the changes and what problem you're trying to solve.*

see #4659 

### Modifications

*Describe the modifications you've done.*
- Check arrtibutes `subject`, `datacontenttype` & `data` before saving a cloudevent. Since they are required in `connectRecord` but optional in cloudevents.
- Use default status message in failure response.

### Documentation

- Does this pull request introduce a new feature?no
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

File: eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/source/connector/HttpSourceConnector.java [hunk 1]
```diff
@@ -83,15 +82,27 @@ private void doInit() {
...
                     .onSuccess(event -> {
                         queue.add(event);
                         log.info("[HttpSourceConnector] Succeed to convert payload into CloudEvent. StatusCode={}", HttpResponseStatus.OK.code());
                         ctx.response().setStatusCode(HttpResponseStatus.OK.code()).end();
                     })
                     .onFailure(t -> {
                         log.error("[HttpSourceConnector] Malformed request. StatusCode={}", HttpResponseStatus.BAD_REQUEST.code(), t);
-                        ctx.response().setStatusCode(HttpResponseStatus.BAD_REQUEST.code()).setStatusMessage(t.getMessage()).end();
+                        ctx.response().setStatusCode(HttpResponseStatus.BAD_REQUEST.code()).end();
                     });
```
Comment (Pil0tXia) [inline eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/source/connector/HttpSourceConnector.java:106]: Why default err message is used instead of "attribute 'subject' cannot be null"?

Comment (Fungx) [reply eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/source/connector/HttpSourceConnector.java:106]: > Why default err message is used instead of "attribute 'subject' cannot be null"?

I think it's not so good to place error message here. In some cases, such as lack of attribute `source`, we get an error message like this from `reader.toEvent()`.
```
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Missing mandatory source attribute
 at [Source: (byte[])"{
    "specversion": "1.0",
    "type":"com.example.someevent",
    "subject":"test_topic",
    "datacontenttype":"text/plain",
    "id": "A234-1234-1234",
    "data": "aa"
}"; line: 8, column: 1]
```
 It contains '\r\n' which cannot be used in the http status message and cause another exception in `setStatusMessage`.
```
2023-12-16 16:18:05,378 ERROR [vert.x-eventloop-thread-0] ContextBase(:) - Unhandled exception
java.lang.IllegalArgumentException: reasonPhrase contains one of the following prohibited characters: \r\n: com.fasterxml.jackson.databind.exc.MismatchedInputException: Missing mandatory source attribute
 at [Source: (byte[])"{
    "specversion": "1.0",
    "type":"com.example.someevent",
    "subject":"test_topic",
    "datacontenttype":"text/plain",
    "id": "A234-1234-1234",
    "data": "aa"
}"; line: 8, column: 1]
	at io.netty.handler.codec.http.HttpResponseStatus.<init>(HttpResponseStatus.java:558) ~[netty-codec-http-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.handler.codec.http.HttpResponseStatus.<init>(HttpResponseStatus.java:546) ~[netty-codec-http-4.1.100.Final.jar:4.1.100.Final]
	at io.vertx.core.http.impl.Http1xServerResponse.setStatusMessage(Http1xServerResponse.java:166) ~[vertx-core-4.4.6.jar:4.4.6]
	at org.apache.eventmesh.connector.http.source.connector.HttpSourceConnector.lambda$null$2(HttpSourceConnector.java:105) ~[main/:?]
```

As a result, the server cannot response to the sender.

**Review by xwm1992 — APPROVED** [review]

**Review by mxsm — APPROVED** [review]
