### PR TITLE
[ISSUE #4820] Bug fix EventHandler not return json

### LINKED ISSUE #4820: [Bug] EventHandler missing return json
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac

### EventMesh version

master

### What happened

EventHandler missing return json

### How to reproduce

Nil

### Debug logs

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

### PR DESCRIPTION
**Pull request by karsonto**
Bug fix EventHandler not return json and add some unit test.

Fixes #4820
Relate #4815

### Motivation

*Explain the content here.*
*Explain why you want to make the changes and what problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

File: eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/AdminHandlerManager.java [hunk 1]
```diff
@@ -117,7 +117,7 @@ public void registerHttpHandler() {
             eventMeshGrpcServer.getEventMeshGrpcConfiguration()));
     }
 
-    private void initHandler(HttpHandler httpHandler) {
+    public void initHandler(HttpHandler httpHandler) {
         EventMeshHttpHandler eventMeshHttpHandler = httpHandler.getClass().getAnnotation(EventMeshHttpHandler.class);
```
Comment (Pil0tXia) [inline eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/AdminHandlerManager.java:121]: Is it a good practice to change a private method's scope just because a test class needs to call it? Maybe we can try to use Reflection.

File: eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/async/CompleteHandler.java [hunk 2]
```diff
@@ -22,6 +22,7 @@
  *
  * @param <T>
  */
+@FunctionalInterface
 public interface CompleteHandler<T> {
```
Comment (Pil0tXia) [inline eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/async/CompleteHandler.java:26]: It seems that there's no lambda usage of this class. What does the addition of this annotation bring?

**Comment by karsonto** [comment]
@Pil0tXia I have successfully implemented the suggestions you provided and made the necessary modifications. Please review.

**Review by Pil0tXia — APPROVED** [review]
LGTM

**Review by mxsm — APPROVED** [review]
LGTM
