### PR TITLE
[ISSUE #3523] fix json serialization issue when using redis

### LINKED ISSUE #3523: [Bug] Json serialization issue when using Redis as storage.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac

### EventMesh version

master

### What happened

when I start the TCP demo and set Redis as storage, the runtime throw json parse exception because the body have not been serialized correctly.
image

see data in Redis
image

### How to reproduce

1. set `eventMesh.storage.plugin.type=redis` in runtime config.
2. add your redis config in `redis-client.properties.
3. start `runtime` via `org.apache.eventmesh.starter.StartUp`.
4. start subscribe demo via `org.apache.eventmesh.tcp.demo.sub.eventmeshmessage.AsyncSubscribe`.
5. start tcp publish demo via `org.apache.eventmesh.tcp.demo.pub.eventmeshmessage.AsyncPublish`.
6. now the error will occur.

### Debug logs
```
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'testAsyncMessage': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (byte[])"{"specversion":"1.0","id":"5683320505","source":"/","type":"eventmeshmessage","subject":"TEST-TOPIC-TCP-ASYNC","protocolversion":"1.0","reqeventmesh2mqtimestamp":"1679593289588","propertymessagereplyto":"notnull","reqsendeventmeship":"[fe80:0:0:0:aede:48ff:fe00:1122%en5]","replyto":"localhost@ProducerGroup-producerPool-9-access#V1_4_0#CI","protocoldesc":"tcp","protocoltype":"eventmeshmessage","ttl":"30000","reqc2eventmeshtimestamp":"1679593289587","data":testAsyncMessage}"; line: 1, column: 477]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'testAsyncMessage': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')

	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391) ~[jackson-core-2.13.0.jar:2.13.0]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:745) ~[jackson-core-2.13.0.jar:2.13.0]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3634) ~[jackson-core-2.13.0.jar:2.13.0]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3607) ~[jackson-core-2.13.0.jar:2.13.0]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._matchToken2(UTF8StreamJsonParser.java:2948) ~[jackson-core-2.13.0.jar:2.13.0]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._matchTrue(UTF8StreamJsonParser.java:2882) ~[jackson-core-2.13.0.jar:2.13.0]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextFieldName(UTF8StreamJsonParser.java:1115) ~[jackson-core-2.13.0.jar:2.13.0]
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer._deserializeContainerNoRecursion(JsonNodeDeserializer.java:440) ~[jackson-databind-2.13.0.jar:2.13.0]
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer$ObjectDeserializer.deserialize(JsonNodeDeserializer.java:122) ~[jackson-databind-2.13.0.jar:2.13.0]
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer$ObjectDeserializer.deserialize(JsonNodeDeserializer.java:105) ~[jackson-databind-2.13.0.jar:2.13.0]
	at com.fasterxml.jackson.databind.DeserializationContext.readValue(DeserializationContext.java:966) ~[jackson-databind-2.13.0.jar:2.13.0]
	at com.fasterxml.jackson.databind.DeserializationContext.readValue(DeserializationContext.java:953) ~[jackson-databind-2.13.0.jar:2.13.0]
	at io.cloudevents.jackson.CloudEventDeserializer.deserialize(CloudEventDeserializer.java:201) ~[cloudevents-json-jackson-2.2.0.jar:?]
	at io.cloudevents.jackson.CloudEventDeserializer.deserialize(CloudEventDeserializer.java:40) ~[cloudevents-json-jackson-2.2.0.jar:?]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[jackson-databind-2.13.0.jar:2.13.0]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4675) ~[jackson-databind-2.13.0.jar:2.13.0]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3691) ~[jackson-databind-2.13.0.jar:2.13.0]
	at io.cloudevents.jackson.JsonFormat.deserialize(JsonFormat.java:99) ~[cloudevents-json-jackson-2.2.0.jar:?]
	at org.apache.eventmesh.storage.redis.cloudevent.CloudEventCodec.lambda$static$1(CloudEventCodec.java:48) ~[eventmesh-storage-redis-1.8.0-release.jar:1.8.0-release]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:383) ~[redisson-3.17.3.jar:3.17.3]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:427) ~[redisson-3.17.3.jar:3.17.3]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:392) ~[redisson-3.17.3.jar:3.17.3]
	at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:86) ~[redisson-3.17.3.jar:3.17.3]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137) ~[redisson-3.17.3.jar:3.17.3]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:94) ~[redisson-3.17.3.jar:3.17.3]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[netty-codec-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.79.Final.jar:4.1.79.Final]
	... 17 more
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by hgaol**
Fixes #3523 .

### Motivation

bug fix for redis storage. After this change, the json be serialized successfully and the consumer can consume the data.
image

### Modifications

*Describe the modifications you've done.*

### Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by mytang0 — CHANGES_REQUESTED** [review]
image

Please pass through the header, do not write hard.

File: eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/tcp/TcpMessageProtocolResolver.java [hunk 1]
```diff
@@ -76,6 +76,7 @@ public static CloudEvent buildEvent(Header header, EventMeshMessage message) thr
             .withId(header.getSeq())
             .withSource(URI.create("/"))
             .withType("eventmeshmessage")
+            .withDataContentType("text/plain")
             .withSubject(topic)
             .withData(content.getBytes(StandardCharsets.UTF_8));
```
Comment (mxsm) [inline eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/tcp/TcpMessageProtocolResolver.java:81]: How about replace StandardCharsets.UTF_8 with Constants.DEFAULT_CHARSET, Consistent code style.
.

**Comment by hgaol** [comment]
> image
> 
> Please pass through the header, do not write hard.

do you mean the Package header? I saw all of current headers are consistent for `EventMeshMessage`, see screenshot below. Or should I add another headers property with type `HashMap` in `EventMeshMessage`, and add all the headers in `Package.Header`?
pls let me know your preference. Thanks!
image

File: eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/tcp/TcpMessageProtocolResolver.java (hunk 1 above)
Comment (hgaol) [reply eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/tcp/TcpMessageProtocolResolver.java:81]: will do. thanks for your advice.

**Comment by mytang0** [comment]
> > image
> > Please pass through the header, do not write hard.
> 
> Hi @mytang0 . Do you mean the Package header? I saw all of current headers are consistent for `EventMeshMessage`, see screenshot below. Or should I add another headers property with type `HashMap` in `EventMeshMessage`, and add all the headers in `Package.Header`? pls let me know your preference. Thanks! image

Hello, that's what i thought

- By default, dataContentType is 'application/json'. The problem with the test case is that the body is not json. So fixing 'text/plain' directly is problematic.
- Therefore, to fundamentally solve this problem. The specified dataContentType that non-json needs to display when the producer publishes a message, and then pass the dataContentType on.

File: eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/tcp/TcpMessageProtocolResolver.java (hunk 1 above)
Comment (hgaol) [reply eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/tcp/TcpMessageProtocolResolver.java]: updated.

**Comment by hgaol** [comment]
> > > image
> > > Please pass through the header, do not write hard.
> > 
> > 
> > Hi @mytang0 . Do you mean the Package header? I saw all of current headers are consistent for `EventMeshMessage`, see screenshot below. Or should I add another headers property with type `HashMap` in `EventMeshMessage`, and add all the headers in `Package.Header`? pls let me know your preference. Thanks! image
> 
> Hello, that's what i thought
> 
> * By default, dataContentType is 'application/json'. The problem with the test case is that the body is not json. So fixing 'text/plain' directly is problematic.
> * Therefore, to fundamentally solve this problem. The specified dataContentType that non-json needs to display when the producer publishes a message, and then pass the dataContentType on.
> * You are right to think about it. We can be simple first, directly in the header.properties

updated. pls let me know if any comment. :)

**Comment by hgaol** [comment]
Hi @mytang0 , any comment?

File: eventmesh-common/src/main/java/org/apache/eventmesh/common/Constants.java [hunk 2]
```diff
@@ -28,6 +28,8 @@ public class Constants {
 
     public static final String DATE_FORMAT_DEFAULT = "yyyy-MM-dd HH:mm:ss";
 
+    public static final String DATA_CONTENT_TYPE = "DataContentType";
```
Comment (mytang0) [inline eventmesh-common/src/main/java/org/apache/eventmesh/common/Constants.java:31]: image

The naming of protocol attributes can be unified.

Comment (xwm1992) [inline eventmesh-common/src/main/java/org/apache/eventmesh/common/Constants.java:31]: the DataContentType key in the CloudEvents protocol must be lowercase，please refer to https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md

**Review by xwm1992 — CHANGES_REQUESTED** [review]

File: eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/tcp/TcpMessageProtocolResolver.java [hunk 3]
```diff
@@ -77,7 +75,11 @@ public static CloudEvent buildEvent(Header header, EventMeshMessage message) thr
             .withSource(URI.create("/"))
             .withType("eventmeshmessage")
             .withSubject(topic)
-            .withData(content.getBytes(StandardCharsets.UTF_8));
+            .withData(content.getBytes(Constants.DEFAULT_CHARSET));
+
+        if (message.getHeaders().containsKey(Constants.DATA_CONTENT_TYPE)) {
+            cloudEventBuilder.withDataContentType(message.getHeaders().get(Constants.DATA_CONTENT_TYPE));
+        }
```
Comment (mytang0) [inline eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/tcp/TcpMessageProtocolResolver.java:83]: Since you implement by adding headers, you also need to set headers in TcpMessageProtocolResolver#buildEventMeshMessage.

```
if (cloudEvent.getDataContentType() != null) {
           eventMeshMessage.getHeaders().put(Constants.DATA_CONTENT_TYPE, cloudEvent.getDataContentType());
}
```

**Review by mytang0 — COMMENTED** [review]
~

File: eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/tcp/TcpMessageProtocolResolver.java (hunk 3 above)
Comment (hgaol) [reply eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/tcp/TcpMessageProtocolResolver.java:84]: resolved. thanks for notification!

File: eventmesh-common/src/main/java/org/apache/eventmesh/common/Constants.java (hunk 2 above)
Comment (hgaol) [reply eventmesh-common/src/main/java/org/apache/eventmesh/common/Constants.java]: resolved.

**Comment by hgaol** [comment]
don't know why CI still error, I didn't change this class and it's succeeded to build on my local machine...
image

**Comment by hgaol** [comment]
> > don't know why CI still error, I didn't change this class and it's succeeded to build on my local machine... image
> 
> you can find this under the `HTTPClientHandler` , because using try-catch with resource, you can remove the `out.write` in the catch block with the `log.error` instead.

seems the github action will link this PR branch to another one, maybe the master branch. In my branch for the PR, the `HTTPClientHandler` is different. You can find the code below.

I didn't use the `checkout` github action for long time, and will find some time to learn if it's by design...

https://github.com/hgaol/incubator-eventmesh/blob/3523/eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/HTTPClientHandler.java#L98

**Comment by hgaol** [comment]
I've created a new PR for fixing the CI issues, see #3544 .

**Review by xwm1992 — APPROVED** [review]

**Review by mytang0 — DISMISSED** [review]
LGTM

**Review by mxsm — COMMENTED** [review]
Hi @hgaol Please rebase master to fix CI not pass

**Comment by mytang0** [comment]
> I've created a new PR for fixing the CI issues, see #3544 .

Already merged, please merge into your branch.

**Comment by hgaol** [comment]
will rebase the newest master, thank you all!

**Review by mytang0 — APPROVED** [review]
